name: 'CodeQL: Autobuild'
description: 'Attempt to automatically build code'
author: 'GitHub'
inputs:
  token:
    default: ${{ github.token }}
  matrix:
    default: ${{ toJson(matrix) }}
runs:
  using: 'node16'
  main: '../lib/autobuild-action.js'